# Generated by Django 2.1.7 on 2019-02-19 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date creation')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish')], max_length=10, verbose_name='language')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Medicine', verbose_name='medicine')),
            ],
            options={
                'verbose_name': 'Medicine Translation',
                'verbose_name_plural': 'Medicine Translations',
            },
        ),
        migrations.CreateModel(
            name='PharmaceuticalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atc_code', models.CharField(blank=True, max_length=255, verbose_name='atc code')),
                ('composition', models.CharField(blank=True, max_length=255, verbose_name='composition')),
                ('composition_es', models.CharField(blank=True, max_length=255, verbose_name='composition (Spanish)')),
                ('composition_pt', models.CharField(blank=True, max_length=255, verbose_name='composition (Portuguese)')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date creation')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Medicine', verbose_name='medicine')),
            ],
            options={
                'verbose_name': 'Pharmaceutical Form',
                'verbose_name_plural': 'Pharmaceutical Forms',
            },
        ),
        migrations.CreateModel(
            name='PharmaceuticalFormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date creation')),
            ],
            options={
                'verbose_name': 'Pharmaceutical Form Type',
                'verbose_name_plural': 'Pharmaceutical Form Types',
            },
        ),
        migrations.CreateModel(
            name='PharmaceuticalFormTypeLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish')], max_length=10, verbose_name='language')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('pharmaceutical_form_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.PharmaceuticalFormType')),
            ],
            options={
                'verbose_name': 'Pharmaceutical Form Type Translation',
                'verbose_name_plural': 'Pharmaceutical Form Type Translations',
            },
        ),
        migrations.AddField(
            model_name='pharmaceuticalform',
            name='pharmaceutical_form_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.PharmaceuticalFormType', verbose_name='pharmaceutical form type'),
        ),
    ]
