# Generated by Django 2.1.7 on 2019-02-19 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='abbreviation')),
                ('year', models.IntegerField(verbose_name='year of publication')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='edition')),
                ('type', models.CharField(choices=[('c', 'Country List'), ('p', 'PAHO List'), ('w', 'WHO List')], max_length=1, verbose_name='Type')),
                ('subtype', models.CharField(blank=True, choices=[('e', 'EML'), ('c', 'EML Children'), ('h', 'High Cost'), ('s', 'Strategic Fund')], max_length=1, null=True, verbose_name='sub-Type')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='observation')),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date creation')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
            },
        ),
        migrations.CreateModel(
            name='ListLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish'), ('en', 'English')], max_length=10, verbose_name='language')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='observation')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='list.List', verbose_name='list')),
            ],
            options={
                'verbose_name': 'List Translation',
                'verbose_name_plural': 'List Translations',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='observation')),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date creation')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='list.List', verbose_name='list')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='list.Section', verbose_name='parent section')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.CreateModel(
            name='SectionLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish'), ('en', 'English')], max_length=10, verbose_name='language')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='observation')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='list.Section', verbose_name='section')),
            ],
            options={
                'verbose_name': 'Section Translation',
                'verbose_name_plural': 'Sections Translations',
            },
        ),
        migrations.CreateModel(
            name='SectionPharmForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_for_children', models.BooleanField(verbose_name='only for children')),
                ('specialist_care_for_children', models.BooleanField(verbose_name='specialist care for children')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='observation')),
                ('observation_es', models.TextField(blank=True, null=True, verbose_name='observation (Spanish)')),
                ('observation_pt', models.TextField(blank=True, null=True, verbose_name='observation (Portuguese)')),
                ('restriction_age', models.CharField(blank=True, max_length=255, null=True, verbose_name='restriction age or weight')),
                ('restriction_age_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='restriction age or weight (Spanish)')),
                ('restriction_age_pt', models.CharField(blank=True, max_length=255, null=True, verbose_name='restriction age or weight (Portuguese)')),
                ('best_evidence', models.BooleanField(verbose_name='The best evidence for effectiveness and safety')),
                ('complementary_list', models.BooleanField(verbose_name='complementary list')),
                ('pharmaceutical_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.PharmaceuticalForm', verbose_name='pharmaceutical form')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='list.Section', verbose_name='section')),
            ],
            options={
                'verbose_name': 'pharmaceutical form',
                'verbose_name_plural': 'pharmaceutical forms',
            },
        ),
    ]
