# Generated by Django 2.1.7 on 2019-02-19 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('abbreviation', models.CharField(blank=True, max_length=50, verbose_name='abbreviation')),
                ('year', models.IntegerField(verbose_name='year of publication')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='edition')),
                ('type', models.CharField(choices=[('c', 'Country List'), ('p', 'PAHO List'), ('w', 'WHO List')], max_length=1, verbose_name='Type')),
                ('subtype', models.CharField(blank=True, choices=[('e', 'EML'), ('c', 'EML Children'), ('h', 'High Cost'), ('s', 'Strategic Fund')], max_length=1, null=True, verbose_name='sub-Type')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='observation')),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date creation')),
                ('xml', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'history',
                'verbose_name_plural': 'histories',
            },
        ),
        migrations.CreateModel(
            name='HistoryLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish'), ('en', 'English')], max_length=10, verbose_name='language')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='observation')),
                ('xml', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='history.History', verbose_name='history')),
            ],
            options={
                'verbose_name': 'history translation',
                'verbose_name_plural': 'history translations',
            },
        ),
    ]
